Language: detect
Port: 25570
MaxLog: 100
MaxChat: 100
EditableExtension:
 - yml
 - txt
EnableDynmap: true
DynmapAddress: ""
ConsoleOnly: true
FileAccess:
SummonCommandAlias: ""
NotificationMax: 100
NotificationIncludeWarnLogLevel: false
